# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Abdullah/Lab_7/Lab_7.srcs/sources_1/bd/mb_hdmi/ip/mb_hdmi_xbar_0/mb_hdmi_xbar_0.xci
# IP: The module: 'mb_hdmi_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Abdullah/Lab_7/Lab_7.gen/sources_1/bd/mb_hdmi/ip/mb_hdmi_xbar_0/mb_hdmi_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_hdmi_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Abdullah/Lab_7/Lab_7.srcs/sources_1/bd/mb_hdmi/ip/mb_hdmi_xbar_0/mb_hdmi_xbar_0.xci
# IP: The module: 'mb_hdmi_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Abdullah/Lab_7/Lab_7.gen/sources_1/bd/mb_hdmi/ip/mb_hdmi_xbar_0/mb_hdmi_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_hdmi_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
