# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7_1_provided_fa23_2/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_hdmi/mb_hdmi.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi || ORIG_REF_NAME==mb_hdmi} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_microblaze_0_0/mb_hdmi_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_microblaze_0_0 || ORIG_REF_NAME==mb_hdmi_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_dlmb_v10_2/mb_hdmi_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_dlmb_v10_2 || ORIG_REF_NAME==mb_hdmi_dlmb_v10_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_ilmb_v10_2/mb_hdmi_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_ilmb_v10_2 || ORIG_REF_NAME==mb_hdmi_ilmb_v10_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_dlmb_bram_if_cntlr_2/mb_hdmi_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==mb_hdmi_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_ilmb_bram_if_cntlr_2/mb_hdmi_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==mb_hdmi_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_lmb_bram_2/mb_hdmi_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_lmb_bram_2 || ORIG_REF_NAME==mb_hdmi_lmb_bram_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_xbar_0/mb_hdmi_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_xbar_0 || ORIG_REF_NAME==mb_hdmi_xbar_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_microblaze_0_axi_periph_0/mb_hdmi_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_hdmi_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_microblaze_0_axi_intc_0/mb_hdmi_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_hdmi_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_mdm_1_2/mb_hdmi_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_mdm_1_2 || ORIG_REF_NAME==mb_hdmi_mdm_1_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_clk_wiz_1_2/mb_hdmi_clk_wiz_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_clk_wiz_1_2 || ORIG_REF_NAME==mb_hdmi_clk_wiz_1_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_rst_clk_wiz_1_100M_2/mb_hdmi_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==mb_hdmi_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_axi_uartlite_0_0/mb_hdmi_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==mb_hdmi_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_hdmi/ip/mb_hdmi_hdmi_text_controller_0_0/mb_hdmi_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_hdmi_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_hdmi_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Users/Abdullah/Lab_7/Lab_7.gen/sources_1/bd/mb_hdmi/mb_hdmi_ooc.xdc
