set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1/microblaze_microblaze_0_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_1/microblaze_microblaze_0_1/microblaze_microblaze_0_1_in_context.xdc id:1 order:EARLY scoped_inst:mb_block_i/microblaze_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1/microblaze_dlmb_v10_1_in_context.xdc id:2 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/dlmb_v10} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1/microblaze_dlmb_v10_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1/microblaze_dlmb_v10_1_in_context.xdc id:3 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/ilmb_v10} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_1/microblaze_dlmb_bram_if_cntlr_1/microblaze_dlmb_bram_if_cntlr_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_1/microblaze_dlmb_bram_if_cntlr_1/microblaze_dlmb_bram_if_cntlr_1_in_context.xdc id:4 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_1/microblaze_ilmb_bram_if_cntlr_1/microblaze_ilmb_bram_if_cntlr_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_1/microblaze_ilmb_bram_if_cntlr_1/microblaze_ilmb_bram_if_cntlr_1_in_context.xdc id:5 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1/microblaze_lmb_bram_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1/microblaze_lmb_bram_1_in_context.xdc id:6 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/lmb_bram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_xbar_0/microblaze_xbar_0/microblaze_xbar_0_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_xbar_0/microblaze_xbar_0/microblaze_xbar_0_in_context.xdc id:7 order:EARLY scoped_inst:mb_block_i/microblaze_0_axi_periph/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_axi_intc_1/microblaze_microblaze_0_axi_intc_1/microblaze_microblaze_0_axi_intc_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_axi_intc_1/microblaze_microblaze_0_axi_intc_1/microblaze_microblaze_0_axi_intc_1_in_context.xdc id:8 order:EARLY scoped_inst:mb_block_i/microblaze_0_axi_intc} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_mdm_1_1/microblaze_mdm_1_1/microblaze_mdm_1_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_mdm_1_1/microblaze_mdm_1_1/microblaze_mdm_1_1_in_context.xdc id:9 order:EARLY scoped_inst:mb_block_i/mdm_1} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_clk_wiz_1_1/microblaze_clk_wiz_1_1/microblaze_clk_wiz_1_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_clk_wiz_1_1/microblaze_clk_wiz_1_1/microblaze_clk_wiz_1_1_in_context.xdc id:10 order:EARLY scoped_inst:mb_block_i/clk_wiz_1} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1_in_context.xdc id:11 order:EARLY scoped_inst:mb_block_i/rst_clk_wiz_1_100M} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_uartlite_0_0/microblaze_axi_uartlite_0_0/microblaze_axi_uartlite_0_0_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_uartlite_0_0/microblaze_axi_uartlite_0_0/microblaze_axi_uartlite_0_0_in_context.xdc id:12 order:EARLY scoped_inst:mb_block_i/axi_uartlite_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_timer_0_0/microblaze_axi_timer_0_0/microblaze_axi_timer_0_0_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_timer_0_0/microblaze_axi_timer_0_0/microblaze_axi_timer_0_0_in_context.xdc id:13 order:EARLY scoped_inst:mb_block_i/timer_usb_axi} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_0/microblaze_axi_gpio_0_0/microblaze_axi_gpio_0_0_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_0/microblaze_axi_gpio_0_0/microblaze_axi_gpio_0_0_in_context.xdc id:14 order:EARLY scoped_inst:mb_block_i/gpio_usb_int} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_1/microblaze_axi_gpio_0_1/microblaze_axi_gpio_0_1_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_1/microblaze_axi_gpio_0_1/microblaze_axi_gpio_0_1_in_context.xdc id:15 order:EARLY scoped_inst:mb_block_i/gpio_usb_rst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_2/microblaze_axi_gpio_0_2/microblaze_axi_gpio_0_2_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_2/microblaze_axi_gpio_0_2/microblaze_axi_gpio_0_2_in_context.xdc id:16 order:EARLY scoped_inst:mb_block_i/gpio_player_pos} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_quad_spi_0_0/microblaze_axi_quad_spi_0_0/microblaze_axi_quad_spi_0_0_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_quad_spi_0_0/microblaze_axi_quad_spi_0_0/microblaze_axi_quad_spi_0_0_in_context.xdc id:17 order:EARLY scoped_inst:mb_block_i/spi_usb} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_3/microblaze_axi_gpio_0_3/microblaze_axi_gpio_0_3_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_axi_gpio_0_3/microblaze_axi_gpio_0_3/microblaze_axi_gpio_0_3_in_context.xdc id:18 order:EARLY scoped_inst:mb_block_i/gpio_deugging} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_GameIP_0_0/microblaze_GameIP_0_0/microblaze_GameIP_0_0_in_context.xdc rfile:../../../../../Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_GameIP_0_0/microblaze_GameIP_0_0/microblaze_GameIP_0_0_in_context.xdc id:19 order:EARLY scoped_inst:mb_block_i/GameIP_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.srcs/constrs_1/imports/lab7_1_provided_fa23_2/mb_usb_hdmi_top.xdc rfile:../../../../../Final_Project.srcs/constrs_1/imports/lab7_1_provided_fa23_2/mb_usb_hdmi_top.xdc id:20} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:21} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0/Clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 33.333 [get_pins mb_block_i/microblaze_0/Dbg_Clk]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 33.333 [get_pins mb_block_i/microblaze_0/Dbg_Update]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/dlmb_v10/LMB_Clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/dlmb_v10]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/ilmb_v10/LMB_Clk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/ilmb_v10]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr/BRAM_Clk_A [get_pins mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr/BRAM_Clk_A]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr/BRAM_Clk_A]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr/LMB_Clk]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr/BRAM_Clk_A [get_pins mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr/BRAM_Clk_A]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr/BRAM_Clk_A]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr/LMB_Clk]
set_property src_info {type:SCOPED_XDC file:5 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mb_block_i/microblaze_0_local_memory/lmb_bram/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mb_block_i/microblaze_0_local_memory/lmb_bram/clkb]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/lmb_bram]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_axi_periph/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_axi_periph/xbar]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_axi_intc/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_axi_intc]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 -name mb_block_i/mdm_1/Dbg_Update_0 [get_pins mb_block_i/mdm_1/Dbg_Update_0]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 -name mb_block_i/mdm_1/Dbg_Clk_0 [get_pins mb_block_i/mdm_1/Dbg_Clk_0]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/mdm_1]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_100MHz [get_ports clk_100MHz]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name mb_block_i/clk_wiz_1/clk_out1 -source [get_pins mb_block_i/clk_wiz_1/clk_in1] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins mb_block_i/clk_wiz_1/clk_out1]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk_100MHz]
set_property src_info {type:SCOPED_XDC file:10 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk_100MHz]
set_property src_info {type:SCOPED_XDC file:10 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/clk_wiz_1]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/rst_clk_wiz_1_100M/slowest_sync_clk]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/rst_clk_wiz_1_100M]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/axi_uartlite_0/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/axi_uartlite_0]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/timer_usb_axi/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/timer_usb_axi]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/gpio_usb_int/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/gpio_usb_int]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/gpio_usb_rst/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/gpio_usb_rst]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/gpio_player_pos/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/gpio_player_pos]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mb_block_i/spi_usb/ext_spi_clk]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mb_block_i/spi_usb/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:17 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/spi_usb]
set_property src_info {type:SCOPED_XDC file:18 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/gpio_deugging/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/gpio_deugging]
set_property src_info {type:SCOPED_XDC file:19 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports HDMI_tmds_clk_n]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports HDMI_tmds_clk_n]
set_property src_info {type:SCOPED_XDC file:19 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports HDMI_tmds_clk_p]
set_property src_info {type:SCOPED_XDC file:19 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports HDMI_tmds_clk_p]
set_property src_info {type:SCOPED_XDC file:19 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_n[0]}]
set_property src_info {type:SCOPED_XDC file:19 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_n[0]}]
set_property src_info {type:SCOPED_XDC file:19 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_n[1]}]
set_property src_info {type:SCOPED_XDC file:19 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_n[1]}]
set_property src_info {type:SCOPED_XDC file:19 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_n[2]}]
set_property src_info {type:SCOPED_XDC file:19 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_n[2]}]
set_property src_info {type:SCOPED_XDC file:19 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_p[0]}]
set_property src_info {type:SCOPED_XDC file:19 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_p[0]}]
set_property src_info {type:SCOPED_XDC file:19 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_p[1]}]
set_property src_info {type:SCOPED_XDC file:19 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_p[1]}]
set_property src_info {type:SCOPED_XDC file:19 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_p[2]}]
set_property src_info {type:SCOPED_XDC file:19 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {HDMI_tmds_data_p[2]}]
set_property src_info {type:SCOPED_XDC file:19 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/GameIP_0]
set_property src_info {type:XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports clk_100MHz]
set_property src_info {type:XDC file:20 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property src_info {type:XDC file:20 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports reset_rtl_0]
set_property src_info {type:XDC file:20 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property src_info {type:XDC file:20 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property src_info {type:XDC file:20 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_usb_int_tri_i[0]}]
set_property src_info {type:XDC file:20 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_miso]
set_property src_info {type:XDC file:20 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_mosi]
set_property src_info {type:XDC file:20 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_sclk]
set_property src_info {type:XDC file:20 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_usb_rst_tri_o[0]}]
set_property src_info {type:XDC file:20 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {usb_spi_ss[0]}]
set_property src_info {type:XDC file:20 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM FALSE [get_ports {HDMI_tmds_data_n[2]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/dlmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/ilmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/lmb_bram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_axi_intc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_xlconcat]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/mdm_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/clk_wiz_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/rst_clk_wiz_1_100M]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/axi_uartlite_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/timer_usb_axi]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/gpio_usb_int]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/gpio_usb_rst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/gpio_player_pos]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/spi_usb]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/gpio_deugging]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/GameIP_0]
