# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Abdullah/Downloads/ECE385/Final Project/Final Project.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1.xci
# IP: The module: 'microblaze_rst_clk_wiz_1_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Abdullah/Downloads/ECE385/Final Project/Final Project.gen/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_1_100M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Abdullah/Downloads/ECE385/Final Project/Final Project.gen/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_1_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Abdullah/Downloads/ECE385/Final Project/Final Project.gen/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_1_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Abdullah/Downloads/ECE385/Final Project/Final Project.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1.xci
# IP: The module: 'microblaze_rst_clk_wiz_1_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Abdullah/Downloads/ECE385/Final Project/Final Project.gen/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_1_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Abdullah/Downloads/ECE385/Final Project/Final Project.gen/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_1_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Abdullah/Downloads/ECE385/Final Project/Final Project.gen/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_1/microblaze_rst_clk_wiz_1_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_1_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
