# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1.xci
# IP: The module: 'microblaze_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.srcs/sources_1/bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1.xci
# IP: The module: 'microblaze_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Abdullah/Downloads/ECE385/Final_Project/Final_Project.gen/sources_1/bd/microblaze/ip/microblaze_ilmb_v10_1/microblaze_ilmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
